version: '3.7'

services:
  plex-exporter:
    image: ruanbekker/plex-exporter
    container_name: 'plex-exporter'
    restart: unless-stopped
    environment:
      - MY_SOURCE=https://github.com/othalla/plex_exporter
      - PLEX_HOST=http://192.168.10.25
      - PLEX_PORT=32400
      - PLEX_API_KEY=x
      - SERVE_PORT=9090
    networks:
      - public
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

networks:
  public:
    name: public
